apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-deployment
  labels:
    app: online-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
        - name: online-shop-container
          image: monudocker334/online-shop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
