apiVersion: v1
kind: Service
metadata:
  name: online-app-svc
  namespace: online-shop
spec:
  selector:
    app: online-shop
  ports:
    - protocol: TCP
      port: 80        # Exposes service on port 80
      targetPort: 80  # Forwards traffic to container port 80
  type: ClusterIP 
